export const AUTHENTICATION_TYPES = {
    AUTHENTICATED: 'AUTHENTICATED',
    UN_AUTHENTICATED: 'UN_AUTHENTICATED',
    NO_AUTH: 'NO_AUTH',
    INITIAL: 'INITIAL'
};

export const LAYOUOT_TYPES = {
    DASHBOARD: 'DASHBOARD',
    NO_LAYOUT: 'NO_LAYOUT'
};
